"""Save portfolio analysis reports (TXT + HTML) for the Reports tab."""
from __future__ import annotations

import html as html_module
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

from src.utils.repo_root import get_repo_root, repo_root_cwd
from src.utils.logger import get_logger

logger = get_logger(__name__)

def _report_dir(user_handle: str) -> Path:
    with repo_root_cwd():
        try:
            import config
            base = config.REPORT_DIR
        except Exception:
            base = get_repo_root() / "reports"
        path = Path(base) / user_handle
        path.mkdir(parents=True, exist_ok=True)
        return path


def _sentiment_counts(sentiment_data: list[dict]) -> dict[str, int]:
    counts = {"positive": 0, "negative": 0, "neutral": 0}
    for item in sentiment_data or []:
        key = str(item.get("sentiment") or "neutral").lower()
        if key in counts:
            counts[key] += 1
        else:
            counts["neutral"] += 1
    return counts


def _risk_rows(visuals: dict, sentiment_data: list[dict]) -> list[dict]:
    sentiment_by_ticker = {}
    for item in sentiment_data or []:
        ticker = str(item.get("ticker") or item.get("symbol") or "").upper()
        if ticker:
            sentiment_by_ticker[ticker] = item.get("sentiment", "neutral")

    rows = []
    for stock in visuals.get("stock_risk_data") or []:
        sym = stock.get("ticker") or stock.get("symbol") or ""
        rows.append({
            "symbol": sym,
            "risk_score": stock.get("risk_score", 50),
            "sentiment": sentiment_by_ticker.get(str(sym).upper(), stock.get("sentiment", "neutral")),
            "shadow_score": stock.get("shadow_score", 0),
            "shadow_signals": stock.get("shadow_signals", ""),
        })
    return rows


def _export_text_only_html(path: Path, report_text: str, brand: str) -> None:
    """Fallback HTML when chart libraries are unavailable."""
    safe = html_module.escape(str(report_text))
    generated = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    path.write_text(
        f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>{brand} Intelligence Report</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; max-width: 960px; margin: 0 auto; padding: 24px; background: #f9fafb; }}
.header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; padding: 28px; border-radius: 10px; text-align: center; }}
pre {{ background: #fff; padding: 24px; border-radius: 10px; white-space: pre-wrap; line-height: 1.55; }}
.footer {{ text-align: center; color: #6b7280; margin-top: 32px; font-size: 0.9rem; }}
</style></head><body>
<div class="header"><h1>{brand} Intelligence Report</h1><p>{generated}</p></div>
<pre>{safe}</pre>
<div class="footer"><p>Generated by {brand} — AI-powered stock intelligence</p></div>
</body></html>""",
        encoding="utf-8",
    )


def save_analysis_report(
    user_handle: str,
    final_state: dict[str, Any],
    holdings: list[dict] | None = None,
) -> dict[str, str]:
    """Write TXT + HTML report files; returns saved filenames."""
    from src.services.portfolio_visuals import build_portfolio_visuals

    try:
        import config
        brand = config.APP_DISPLAY_NAME
        report_prefix = config.REPORT_FILE_PREFIX
    except Exception:
        brand = "AlphaHive"
        report_prefix = "alphahive_report"

    tickers = final_state.get("tickers") or []
    report_text = final_state.get("final_report") or "No report text generated."
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"{report_prefix}_{timestamp}"
    target_dir = _report_dir(user_handle)

    txt_path = target_dir / f"{base_name}.txt"
    header = (
        "=" * 80 + "\n"
        + " " * 25 + f"{brand.upper()} INTELLIGENCE REPORT\n"
        + " " * 30 + f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        + "=" * 80 + "\n\n"
    )
    txt_path.write_text(header + str(report_text), encoding="utf-8")

    html_path = target_dir / f"{base_name}.html"

    try:
        from utils.report_visualizer import ReportVisualizer

        visuals = build_portfolio_visuals(tickers, holdings)
        visualizer = ReportVisualizer()
        figures = []

        sentiment_data = final_state.get("sentiment_data") or []
        sentiment = _sentiment_counts(sentiment_data)
        if sum(sentiment.values()) > 0:
            figures.append(visualizer.create_sentiment_pie_chart(sentiment))

        risk_rows = _risk_rows(visuals, sentiment_data)
        if risk_rows:
            figures.append(visualizer.create_portfolio_heatmap(risk_rows))

        corr = visuals.get("correlation_matrix") or {}
        if corr:
            corr_df = pd.DataFrame(corr)
            if not corr_df.empty:
                figures.append(visualizer.create_correlation_heatmap(corr_df))

        visualizer.export_to_html(figures, str(report_text), html_path)
    except Exception as exc:
        logger.warning("Chart export unavailable (%s); saving text-only HTML.", exc)
        _export_text_only_html(html_path, report_text, brand)

    return {"txt": txt_path.name, "html": html_path.name}
